name: sff
description: A command-line application that implements the functionality of the sff_lib library.
version: 0.0.2
repository: https://github.com/yuraMovsesyan/sff_cli

environment:
  sdk: ^3.2.6

dependencies:
  args: ^2.4.2
  path: ^1.9.0
  crypto: ^3.0.3
  sff_lib: ^0.0.8

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
