name: sff
description: A command-line application that implements the functionality of the sff_lib library.
version: 0.0.2
repository: https://github.com/yuraMovsesyan/sff_cli

environment:
  sdk: ^3.2.6

dependencies:
  args: ^2.4.2
  path: ^1.9.0
  crypto:
  sff_lib: 
    path: sff_lib/

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
