install:
	@install -d $(DESTDIR)/usr/share/sff/
	@install -d $(DESTDIR)/usr/bin
	@install -v -m 755 sff $(DESTDIR)/usr/bin/
    
remove:
	@echo "Removing..."
	@rm -rf $(DESTDIR)/usr/share/sff
	@rm -rf $(DESTDIR)/usr/bin/sff
	@echo "Done!"