name: miomit-sff-cli0
version: 0.0.4
summary: Command-line application
description: |
  Command-line application that implements the functionality of the sff library. 

confinement: strict
base: core24
grade: stable

parts:
  miomit-sff-cli0:
    plugin: dump
    source: org.snap.sff.tar.gz

apps:
  miomit-sff-cli0:
    command: sff
    plugs:
    - removable-media
    - home
    - cifs-mount
    - mount-observe
    - raw-volume